language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
before_script:
  - composer require kenjis/ci-phpunit-test --dev
  - php vendor/kenjis/ci-phpunit-test/install.php
script:
  - cd application/tests/
  - phpunit -v
after_success:
  - coveralls